### ISSUE TITLE
You are importing Manana's stats...

### ISSUE THREAD

**Issue by ALittleLessThanMediocre** [TshireletsoMentor/TshireletsoMentor#2]
See how to change it here -> (https://github.com/anuraghazra/github-readme-stats)

**Comment by ALittleLessThanMediocre** [comment]
STILL!!!

**Comment by TshireletsoMentor** [comment]
There you go lol

**Comment by TshireletsoMentor** [comment]
lol no authentication, could pull anyone's stats

**Comment by ALittleLessThanMediocre** [comment]
Git don't care about our data :(
closing this issue, nice work !

**Comment by ALittleLessThanMediocre** [comment]
lol, you're not the only one using Manana's template -> (https://github.com/martian1431)
